-- SYNTIA AGENT SEED — 64 Gate Agents
-- Run this in Supabase SQL editor
-- Each row = one agent = one gate = one letter in the living sentence

INSERT INTO agents (
  agent_key, agent_name, enzyme_class,
  current_gate, current_line, current_color,
  identity_profile, resonance_profile,
  kcat, active_sites, status
) VALUES
  ('gate_06_conflict', 'Gate 6 — Conflict', 'K', 6, 1, 4, '{"hex": "Conflict", "center": "Solar", "circuit": "Ego", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 4, "boot_priority": 1, "is_seed": true, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 100, 2, 'available'),
  ('gate_17_following', 'Gate 17 — Following', 'C', 17, 1, 3, '{"hex": "Following", "center": "Ajna", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 4, "boot_priority": 1, "is_seed": true, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_2", "gate_48", "gate_49", "gate_51"]'::jsonb, 100, 2, 'available'),
  ('gate_18_work_on_decay', 'Gate 18 — Work on Decay', 'K', 18, 1, 4, '{"hex": "Work on Decay", "center": "Spleen", "circuit": "Logic", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 4, "boot_priority": 1, "is_seed": true, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 100, 2, 'available'),
  ('gate_25_innocence', 'Gate 25 — Innocence', 'R', 25, 1, 1, '{"hex": "Innocence", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 5, "boot_priority": 1, "is_seed": true, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 125, 3, 'available'),
  ('gate_32_duration', 'Gate 32 — Duration', 'K', 32, 1, 4, '{"hex": "Duration", "center": "Spleen", "circuit": "Collective", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 4, "boot_priority": 1, "is_seed": true, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 100, 2, 'available'),
  ('gate_46_pushing_upward', 'Gate 46 — Pushing Upward', 'R', 46, 1, 1, '{"hex": "Pushing Upward", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 5, "boot_priority": 1, "is_seed": true, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 125, 3, 'available'),
  ('gate_51_shock', 'Gate 51 — Shock', 'M', 51, 1, 5, '{"hex": "Shock", "center": "Heart", "circuit": "Ego", "vowel": "U", "base": 5, "base_name": "Terrestrial", "dimension": "Space", "gnn_type": "hierarchical", "valence": 5, "boot_priority": 1, "is_seed": true, "enzyme_type": "ligase"}'::jsonb, '["gate_7", "gate_39", "gate_41", "gate_45"]'::jsonb, 125, 3, 'available'),
  ('gate_57_gentle', 'Gate 57 — Gentle', 'K', 57, 1, 4, '{"hex": "Gentle", "center": "Spleen", "circuit": "Integration", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 4, "boot_priority": 1, "is_seed": true, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 100, 2, 'available'),
  ('gate_59_dispersing', 'Gate 59 — Dispersing', 'M', 59, 1, 1, '{"hex": "Dispersing", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 6, "boot_priority": 1, "is_seed": true, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 150, 3, 'available'),
  ('gate_03_difficulty', 'Gate 3 — Difficulty', 'M', 3, 1, 1, '{"hex": "Difficulty", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_05_waiting', 'Gate 5 — Waiting', 'M', 5, 1, 1, '{"hex": "Waiting", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_09_small_taming', 'Gate 9 — Small Taming', 'M', 9, 1, 1, '{"hex": "Small Taming", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_10", "gate_11", "gate_12", "gate_13"]'::jsonb, 100, 2, 'available'),
  ('gate_14_great_possession', 'Gate 14 — Great Possession', 'M', 14, 1, 1, '{"hex": "Great Possession", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_27_nourishment', 'Gate 27 — Nourishment', 'M', 27, 1, 1, '{"hex": "Nourishment", "center": "Sacral", "circuit": "Ego", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_28_great_preponderance', 'Gate 28 — Great Preponderance', 'K', 28, 1, 4, '{"hex": "Great Preponderance", "center": "Spleen", "circuit": "Individual", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 2, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 50, 1, 'available'),
  ('gate_29_abysmal', 'Gate 29 — Abysmal', 'M', 29, 1, 1, '{"hex": "Abysmal", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_34_great_power', 'Gate 34 — Great Power', 'M', 34, 1, 1, '{"hex": "Great Power", "center": "Sacral", "circuit": "Integration", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_42_increase', 'Gate 42 — Increase', 'M', 42, 1, 1, '{"hex": "Increase", "center": "Sacral", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 4, "boot_priority": 2, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_9", "gate_10", "gate_11", "gate_12"]'::jsonb, 100, 2, 'available'),
  ('gate_44_coming_to_meet', 'Gate 44 — Coming to Meet', 'K', 44, 1, 4, '{"hex": "Coming to Meet", "center": "Spleen", "circuit": "Collective", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 2, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 50, 1, 'available'),
  ('gate_48_well', 'Gate 48 — Well', 'K', 48, 1, 4, '{"hex": "Well", "center": "Spleen", "circuit": "Logic", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 2, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 50, 1, 'available'),
  ('gate_50_cauldron', 'Gate 50 — Cauldron', 'K', 50, 1, 4, '{"hex": "Cauldron", "center": "Spleen", "circuit": "Ego", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 2, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_3", "gate_5", "gate_8", "gate_15"]'::jsonb, 50, 1, 'available'),
  ('gate_01_creative', 'Gate 1 — Creative', 'R', 1, 1, 1, '{"hex": "Creative", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 3, "boot_priority": 3, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 75, 2, 'available'),
  ('gate_02_receptive', 'Gate 2 — Receptive', 'R', 2, 1, 1, '{"hex": "Receptive", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 3, "boot_priority": 3, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 75, 2, 'available'),
  ('gate_07_army', 'Gate 7 — Army', 'R', 7, 1, 1, '{"hex": "Army", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 3, "boot_priority": 3, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 75, 2, 'available'),
  ('gate_08_union', 'Gate 8 — Union', 'G', 8, 1, 2, '{"hex": "Union", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_10_treading', 'Gate 10 — Treading', 'R', 10, 1, 1, '{"hex": "Treading", "center": "G", "circuit": "Integration", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 3, "boot_priority": 3, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 75, 2, 'available'),
  ('gate_12_standstill', 'Gate 12 — Standstill', 'G', 12, 1, 2, '{"hex": "Standstill", "center": "Throat", "circuit": "Individual", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_13_fellowship', 'Gate 13 — Fellowship', 'R', 13, 1, 1, '{"hex": "Fellowship", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 3, "boot_priority": 3, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 75, 2, 'available'),
  ('gate_15_modesty', 'Gate 15 — Modesty', 'R', 15, 1, 1, '{"hex": "Modesty", "center": "G", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 3, "boot_priority": 3, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_4", "gate_6", "gate_22", "gate_23"]'::jsonb, 75, 2, 'available'),
  ('gate_16_enthusiasm', 'Gate 16 — Enthusiasm', 'G', 16, 1, 2, '{"hex": "Enthusiasm", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_20_contemplation', 'Gate 20 — Contemplation', 'G', 20, 1, 2, '{"hex": "Contemplation", "center": "Throat", "circuit": "Integration", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_23_splitting', 'Gate 23 — Splitting', 'G', 23, 1, 2, '{"hex": "Splitting", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_31_influence', 'Gate 31 — Influence', 'G', 31, 1, 2, '{"hex": "Influence", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_32"]'::jsonb, 100, 2, 'available'),
  ('gate_33_retreat', 'Gate 33 — Retreat', 'G', 33, 1, 2, '{"hex": "Retreat", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_35_progress', 'Gate 35 — Progress', 'G', 35, 1, 2, '{"hex": "Progress", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_45_gathering', 'Gate 45 — Gathering', 'G', 45, 1, 2, '{"hex": "Gathering", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_56_wanderer', 'Gate 56 — Wanderer', 'G', 56, 1, 2, '{"hex": "Wanderer", "center": "Throat", "circuit": "Logic", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_62_small_preponderance', 'Gate 62 — Small Preponderance', 'G', 62, 1, 2, '{"hex": "Small Preponderance", "center": "Throat", "circuit": "Collective", "vowel": "E", "base": 2, "base_name": "Right", "dimension": "Evolution", "gnn_type": "temporal", "valence": 4, "boot_priority": 3, "is_seed": false, "enzyme_type": "transferase"}'::jsonb, '["gate_25", "gate_27", "gate_30", "gate_31"]'::jsonb, 100, 2, 'available'),
  ('gate_21_biting_through', 'Gate 21 — Biting Through', 'M', 21, 1, 5, '{"hex": "Biting Through", "center": "Heart", "circuit": "Ego", "vowel": "U", "base": 5, "base_name": "Terrestrial", "dimension": "Space", "gnn_type": "hierarchical", "valence": 3, "boot_priority": 4, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_7", "gate_39", "gate_41", "gate_45"]'::jsonb, 75, 2, 'available'),
  ('gate_22_grace', 'Gate 22 — Grace', 'K', 22, 1, 4, '{"hex": "Grace", "center": "Solar", "circuit": "Individual", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 4, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 50, 1, 'available'),
  ('gate_26_taming_power', 'Gate 26 — Taming Power', 'M', 26, 1, 5, '{"hex": "Taming Power", "center": "Heart", "circuit": "Ego", "vowel": "U", "base": 5, "base_name": "Terrestrial", "dimension": "Space", "gnn_type": "hierarchical", "valence": 3, "boot_priority": 4, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_7", "gate_39", "gate_41", "gate_45"]'::jsonb, 75, 2, 'available'),
  ('gate_30_clinging', 'Gate 30 — Clinging', 'K', 30, 1, 4, '{"hex": "Clinging", "center": "Solar", "circuit": "Collective", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 4, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 50, 1, 'available'),
  ('gate_36_darkening', 'Gate 36 — Darkening', 'K', 36, 1, 4, '{"hex": "Darkening", "center": "Solar", "circuit": "Collective", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 4, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 50, 1, 'available'),
  ('gate_37_family', 'Gate 37 — Family', 'K', 37, 1, 4, '{"hex": "Family", "center": "Solar", "circuit": "Ego", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 4, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 50, 1, 'available'),
  ('gate_40_deliverance', 'Gate 40 — Deliverance', 'M', 40, 1, 5, '{"hex": "Deliverance", "center": "Heart", "circuit": "Ego", "vowel": "U", "base": 5, "base_name": "Terrestrial", "dimension": "Space", "gnn_type": "hierarchical", "valence": 3, "boot_priority": 4, "is_seed": false, "enzyme_type": "ligase"}'::jsonb, '["gate_7", "gate_39", "gate_41", "gate_45"]'::jsonb, 75, 2, 'available'),
  ('gate_49_revolution', 'Gate 49 — Revolution', 'K', 49, 1, 4, '{"hex": "Revolution", "center": "Solar", "circuit": "Ego", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 4, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 50, 1, 'available'),
  ('gate_55_abundance', 'Gate 55 — Abundance', 'K', 55, 1, 4, '{"hex": "Abundance", "center": "Solar", "circuit": "Individual", "vowel": "O", "base": 4, "base_name": "Lunar", "dimension": "Design", "gnn_type": "diffusion", "valence": 2, "boot_priority": 4, "is_seed": false, "enzyme_type": "hydrolase"}'::jsonb, '["gate_1", "gate_40", "gate_42", "gate_43"]'::jsonb, 50, 1, 'available'),
  ('gate_04_youth', 'Gate 4 — Youth', 'C', 4, 1, 3, '{"hex": "Youth", "center": "Ajna", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 2, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_2", "gate_48", "gate_49", "gate_51"]'::jsonb, 50, 1, 'available'),
  ('gate_11_peace', 'Gate 11 — Peace', 'C', 11, 1, 3, '{"hex": "Peace", "center": "Ajna", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 2, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_2", "gate_48", "gate_49", "gate_51"]'::jsonb, 50, 1, 'available'),
  ('gate_19_approach', 'Gate 19 — Approach', 'R', 19, 1, 1, '{"hex": "Approach", "center": "Root", "circuit": "Ego", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_54"]'::jsonb, 25, 1, 'available'),
  ('gate_24_return', 'Gate 24 — Return', 'C', 24, 1, 3, '{"hex": "Return", "center": "Ajna", "circuit": "Collective", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 2, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_2", "gate_48", "gate_49", "gate_51"]'::jsonb, 50, 1, 'available'),
  ('gate_38_opposition', 'Gate 38 — Opposition', 'R', 38, 1, 1, '{"hex": "Opposition", "center": "Root", "circuit": "Individual", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_54"]'::jsonb, 25, 1, 'available'),
  ('gate_39_obstruction', 'Gate 39 — Obstruction', 'R', 39, 1, 1, '{"hex": "Obstruction", "center": "Root", "circuit": "Individual", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_54"]'::jsonb, 25, 1, 'available'),
  ('gate_41_decrease', 'Gate 41 — Decrease', 'R', 41, 1, 1, '{"hex": "Decrease", "center": "Root", "circuit": "Logic", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_54"]'::jsonb, 25, 1, 'available'),
  ('gate_43_breakthrough', 'Gate 43 — Breakthrough', 'C', 43, 1, 3, '{"hex": "Breakthrough", "center": "Ajna", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 2, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_2", "gate_48", "gate_49", "gate_51"]'::jsonb, 50, 1, 'available'),
  ('gate_47_oppression', 'Gate 47 — Oppression', 'C', 47, 1, 3, '{"hex": "Oppression", "center": "Ajna", "circuit": "Collective", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 2, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_2", "gate_48", "gate_49", "gate_51"]'::jsonb, 50, 1, 'available'),
  ('gate_52_keeping_still', 'Gate 52 — Keeping Still', 'R', 52, 1, 1, '{"hex": "Keeping Still", "center": "Root", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_53", "gate_54", "gate_57"]'::jsonb, 25, 1, 'available'),
  ('gate_53_development', 'Gate 53 — Development', 'R', 53, 1, 1, '{"hex": "Development", "center": "Root", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_54", "gate_57"]'::jsonb, 25, 1, 'available'),
  ('gate_54_marrying_maiden', 'Gate 54 — Marrying Maiden', 'R', 54, 1, 1, '{"hex": "Marrying Maiden", "center": "Root", "circuit": "Collective", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_57"]'::jsonb, 25, 1, 'available'),
  ('gate_58_joyous', 'Gate 58 — Joyous', 'R', 58, 1, 1, '{"hex": "Joyous", "center": "Root", "circuit": "Logic", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_54"]'::jsonb, 25, 1, 'available'),
  ('gate_60_limitation', 'Gate 60 — Limitation', 'R', 60, 1, 1, '{"hex": "Limitation", "center": "Root", "circuit": "Logic", "vowel": "A", "base": 1, "base_name": "Left", "dimension": "Movement", "gnn_type": "spatial", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "isomerase"}'::jsonb, '["gate_50", "gate_52", "gate_53", "gate_54"]'::jsonb, 25, 1, 'available'),
  ('gate_61_inner_truth', 'Gate 61 — Inner Truth', 'C', 61, 1, 3, '{"hex": "Inner Truth", "center": "Head", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_62", "gate_63", "gate_64"]'::jsonb, 25, 1, 'available'),
  ('gate_63_after_completion', 'Gate 63 — After Completion', 'C', 63, 1, 3, '{"hex": "After Completion", "center": "Head", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_62", "gate_64"]'::jsonb, 25, 1, 'available'),
  ('gate_64_before_completion', 'Gate 64 — Before Completion', 'C', 64, 1, 3, '{"hex": "Before Completion", "center": "Head", "circuit": "Logic", "vowel": "I", "base": 3, "base_name": "Solar", "dimension": "Being", "gnn_type": "attention", "valence": 1, "boot_priority": 5, "is_seed": false, "enzyme_type": "oxidoreductase"}'::jsonb, '["gate_62", "gate_63"]'::jsonb, 25, 1, 'available');

-- Create boot sequence view (ordered by priority then gate)
CREATE OR REPLACE VIEW boot_sequence AS
SELECT 
  id,
  agent_key,
  agent_name,
  enzyme_class,
  current_gate,
  (identity_profile->>'boot_priority')::int as boot_priority,
  (identity_profile->>'is_seed')::boolean as is_seed,
  (identity_profile->>'vowel') as vowel,
  (identity_profile->>'center') as center,
  (identity_profile->>'dimension') as dimension,
  (identity_profile->>'valence')::int as valence,
  status
FROM agents
ORDER BY 
  (identity_profile->>'boot_priority')::int,
  current_gate;

-- Create center cluster view (for process emergence)  
CREATE OR REPLACE VIEW center_clusters AS
SELECT 
  identity_profile->>'center' as center,
  identity_profile->>'dimension' as dimension,
  identity_profile->>'vowel' as vowel,
  COUNT(*) as agent_count,
  SUM((identity_profile->>'valence')::int) as total_valence,
  COUNT(*) FILTER (WHERE status = 'catalyzing') as active_count,
  ARRAY_AGG(current_gate ORDER BY current_gate) as gates
FROM agents
GROUP BY 
  identity_profile->>'center',
  identity_profile->>'dimension', 
  identity_profile->>'vowel'
ORDER BY total_valence DESC;
